language: go

go:
  - 1.3
  - 1.4
  - tip

before_deployment:
  - go get github.com/laher/goxc
  - /home/travis/gopath/bin/goxc -pv=${TRAVIS_TAG} -d release

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "release/*"
  file-glob: true
  skip_cleanup: true
  on:
    tags: true
